team: frontenddevs
pipeline: accessibility-guidelines
slack_channel: "#frontend-alerts"

tasks:
- type: deploy-cf
  name: deploy to dev
  api: ((cloudfoundry.api-dev))
  space: dev
  manifest: manifest-dev.yml

- type: deploy-cf
  name: deploy to live
  api: ((cloudfoundry.api-live))
  space: live
  manifest: manifest-live.yml
